using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SimplCalCon.Domain.Scheduling;

namespace SimplCalCon.Infrastructure.Persistence.Configurations;

public class ScheduleMessageConfiguration : IEntityTypeConfiguration<ScheduleMessage>
{
    public void Configure(EntityTypeBuilder<ScheduleMessage> builder)
    {
        builder.ToTable("ScheduleMessages");
        builder.HasKey(m => m.Id);

        builder.Property(m => m.ResourceName).IsRequired().HasMaxLength(256);
        builder.Property(m => m.Blob).IsRequired();
        builder.Property(m => m.Method).IsRequired().HasMaxLength(20);
        builder.Property(m => m.CreatedAt).IsRequired();
        // ConcurrencyToken is configured + regenerated by the DbContext convention (IHasConcurrencyToken).

        builder.HasOne(m => m.Inbox)
            .WithMany(i => i.Messages)
            .HasForeignKey(m => m.CollectionId)
            .OnDelete(DeleteBehavior.Cascade);

        builder.HasIndex(m => new { m.CollectionId, m.ResourceName }).IsUnique();
        builder.HasIndex(m => new { m.CollectionId, m.ChangeNumber });
    }
}
