{{- if not .Values.database.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "simplcalcon.secretName" . }}
  labels:
    {{- include "simplcalcon.labels" . | nindent 4 }}
type: Opaque
stringData:
  connection-string: {{ .Values.database.connectionString | quote }}
  {{- with .Values.bootstrap.platformAdminPassword }}
  platform-admin-password: {{ . | quote }}
  {{- end }}
{{- end }}
